filters:
  - label: ⚙ feat
    regexs:
      - /feat/i
    events: [issues, pull_request]
    targets: [title]
  - label: 🛠️ fix
    regexs:
      - /fix/i
    events: [issues, pull_request]
    targets: [title]
  - label: 💻 style
    regexs:
      - /style/i
    events: [issues, pull_request]
    targets: [title]
  - label: 🚀 chore
    regexs:
      - /chore/i
    events: [issues, pull_request]
    targets: [title]
