name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign - PR 만든 사람
          reviewers: m9-m9,nno3onn # 리뷰어 추가
          exclude-author: true # 작성자는 리뷰어 제외
