name: Review Assign

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: read
  pull-requests: write  # PR 수정 권한
  issues: write         # assignee 설정 권한

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign - PR 만든 사람
          reviewers: m9-m9,nno3onn # 리뷰어 추가
